### ISSUE TITLE
Dropbox: will not accept 0-byte files

### ISSUE THREAD

**Issue by vlj91** [alces-software/clusterware-storage#1]
0-byte files do not seem to be accepted, however can upload the same file via web-interface: 

```
[root@login1(cluster1) ~]# alces storage put testfile testfile
alces storage put: ERROR: 400 - Bad input parameter - No upload with upload_id [] found
```

After uploading via web interface:

```
[root@login1(cluster1) ~]# alces storage list data/
2016-02-16 15:14          0   testfile
```

**Comment by mjtko** [comment]
This will be fixed for future builds of Clusterware.  The update made in https://github.com/alces-software/clusterware-dropbox-cli/commit/381bea18882b86b3ebd5dd0ce4b60e55bb5615ea special-cases 0-byte files and allows them to be uploaded.  This change has been rolled out to updated Serviceware tarballs.
