### ISSUE TITLE
Can't view certain buckets

### ISSUE THREAD

**Issue by sierra-tango-echo** [alces-software/clusterware-storage#2]
When looking at alces s3 account some buckets work:

[alces@ip-10-75-0-15(sfn2) ~]$ alces storage ls s3://alces
                       DIR   s3://alces/custodian/
                       DIR   s3://alces/dell210/
                       DIR   s3://alces/etc/
                       DIR   s3://alces/test1/

some dont:
[alces@ip-10-75-0-15(sfn2) ~]$ alces storage ls s3://images.alces-software.com/

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  following lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Invoked as: /opt/clusterware/opt/s3cmd/s3cmd -c /home/alces/.config/clusterware/storage/alces-s32.s3.cfg ls s3://images.alces-software.com/
Problem: UnboundLocalError: local variable 'conn' referenced before assignment
S3cmd:   1.6.0
python:   2.7.5 (default, Nov 20 2015, 02:00:19)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
environment LANG=en_GB.UTF-8

Traceback (most recent call last):
  File "/opt/clusterware/opt/s3cmd/s3cmd", line 2805, in <module>
    rc = main()
  File "/opt/clusterware/opt/s3cmd/s3cmd", line 2713, in main
    rc = cmd_func(args)
  File "/opt/clusterware/opt/s3cmd/s3cmd", line 120, in cmd_ls
    subcmd_bucket_list(s3, uri)
  File "/opt/clusterware/opt/s3cmd/s3cmd", line 153, in subcmd_bucket_list
    response = s3.bucket_list(bucket, prefix = prefix)
  File "/opt/clusterware/opt/s3cmd/S3/S3.py", line 293, in bucket_list
    for dirs, objects in self.bucket_list_streaming(bucket, prefix, recursive, uri_params):
  File "/opt/clusterware/opt/s3cmd/S3/S3.py", line 320, in bucket_list_streaming
    response = self.bucket_list_noparse(bucket, prefix, recursive, uri_params)
  File "/opt/clusterware/opt/s3cmd/S3/S3.py", line 339, in bucket_list_noparse
    response = self.send_request(request)
  File "/opt/clusterware/opt/s3cmd/S3/S3.py", line 1084, in send_request
    conn.counter = ConnMan.conn_max_counter
UnboundLocalError: local variable 'conn' referenced before assignment

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  above lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

maybe its something about those buckets in particular? (packages.alces-software.com does the same)

**Comment by mjtko** [comment]
Seems to be a bug in s3cmd (github.com/s3tools/s3cmd/issues/437 etc.): bucket names containing a dot fail due to the wildcard cert served up by Amazon.  e.g. visiting the following in a browser will also generate a cert failure: https://packages.alces-software.com.s3.amazonaws.com/

This was originally fixed, but Python 2.7.5 has recently received an update to the SSL library which rendered the original fix broken again. Yay. Since then, s3cmd has been updated again to fix this.

The quickest fix (and possibly most reliable?) is to set `check_ssl_certificate = False` in the configuration file when configuring an S3 target (specifically if the host is `s3.amazonaws.com`) as this is effectively what the patch implemented in `s3md` actually does!
