### ISSUE TITLE
Tab completion for files

### ISSUE THREAD

**Issue by vlj91** [alces-software/clusterware-storage#6]
The storage utilities already have tab completion for the available commands, but no tab completion for files when using, for example - `put`: 

`alces storage put con..` - won't pick up the `content.el7.tgz` file in my cwd. 

Additionally, along the same lines - being able to tab complete folders/bucket names would be wonderful. 

Is this something worth adding?

**Comment by mjtko** [comment]
This issue was moved to alces-software/clusterware#82
